### ISSUE TITLE
Make Streamnesia pull payloads from the repo

### ISSUE THREAD

**Issue by petrspelos** [petrspelos/Streamnesia#4]
## Summary

This will make sure that people playing Streamnesia will always get the latest payloads and fixes to payloads in this repo.

## Implementation

Any front-end C# application (ConsoleApp & WebApp) should first call a module that will sync payloads with this repository.
This will most likely require another configuration JSON file which will contain GitHub raw file URLs to individual payloads. The Application can then decide to either download missing payloads, or overwrite existing ones.

If there is no Internet connection, Streamnesia should simply skip this step. That's also why the payloads are downloaded and stored locally.

**Comment by ItsTrigger** [comment]
Would it be possible to make it easier to disable this feature?

I've been making a lot of use of this mod on stream, with a lot of custom effects created by a viewer of mine, however It's required that I use the original 1.0 release as any effort to block the mod's connection to the internet just causes it to hang and never connect to chat.

This hasn't been an issue so far, however the 2.0 release adds things I'd definitely be interested in trying out.

Very good job on the mod, though. It's been a lot of fun playing this!

**Comment by petrspelos** [comment]
Hello, @ItsTrigger!
You're right, this and plenty of other improvements are definitely planned for the next minor release.
Thanks for reporting. :heart:
